# SPDX-License-Identifier: GPL-2.0-only
# waveUSBCAN_b DKMS package metadata
# Copyright (C) 2026 Jürgen W. Sievers and OpenAI ChatGPT
# Authors: Jürgen W. Sievers; OpenAI ChatGPT

PACKAGE_NAME="waveUSBCAN_b"
PACKAGE_VERSION="0.1.11"
BUILT_MODULE_NAME[0]="waveusbcan_b"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make KERNELDIR=/lib/modules/${kernelver}/build"
